-- CreateTable
CREATE TABLE "ts_bpharmacy_2024" (
    "sno" DECIMAL NOT NULL,
    "inst_code" TEXT,
    "institute_name" TEXT,
    "place" TEXT,
    "dist_code" TEXT,
    "co_education" TEXT,
    "college_type" TEXT,
    "year" TEXT,
    "branch_code" TEXT,
    "branch_name" TEXT,
    "oc_boys" DECIMAL,
    "oc_girls" DECIMAL,
    "bc_a_boys" DECIMAL,
    "bc_a_girls" DECIMAL,
    "bc_b_boys" DECIMAL,
    "bc_b_girls" DECIMAL,
    "bc_c_boys" DECIMAL,
    "bc_c_girls" DECIMAL,
    "bc_d_boys" DECIMAL,
    "bc_d_girls" DECIMAL,
    "bc_e_boys" DECIMAL,
    "bc_e_girls" DECIMAL,
    "sc_boys" DECIMAL,
    "sc_girls" DECIMAL,
    "st_boys" DECIMAL,
    "st_girls" DECIMAL,
    "ews_gen_ou" DECIMAL,
    "ews_girls_ou" DECIMAL,
    "tuition_fee" DECIMAL,
    "affiliated_to" TEXT,

    CONSTRAINT "ts_bpharmacy_2024_pkey" PRIMARY KEY ("sno")
);
